version: '2'
services:
  worker:
    build: .
    volumes:
      - .:/code
    environment:
      - HOST_IP=${HOST_IP}
      - REDIS_HOST_IP=${REDIS_HOST_IP}
      - ETCD_HOST_IP=${ETCD_HOST_IP}
      - SERVICE_NAME=PushlWorker
      - STAGE=${STAGE}
      - CONFIG_HOST=${CONFIG_HOST}
      - CONFIG_PORT=${CONFIG_PORT}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
      - "etcd.digitalfunk.io:${ETCD_HOST_IP}"
      - "redis.digitalfunk.io:${REDIS_HOST_IP}"
